version: "3.3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - 5000:5000
    environment:
      - MONGO_HOST=mongo
      #- REST_URL=http://rest:5000/people/
    depends_on:
      - rest
    volumes:
      - ./:/app
  rest:
    build:
      context: .
      dockerfile: Dockerfile.rest
    ports:
      - 8000:5000
    environment:
      - MONGO_HOST=mongo
    depends_on:
      - mongo
    volumes:
      - ./:/app
  mongo:
    image: "mongo:4"
    ports:
      - 27017:27017